# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '59 1,7,13,19 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        env:
          TZ: Asia/Hong_Kong
        run: |
          yarn install --production
          yarn start
          find docs -type d | sort | sed 's/^docs/https:\/\/www.jacebean.com/' > docs/sitemap.txt
          find docs -name '*.html' | sort | sed 's/^docs/https:\/\/www.jacebean.com/' >> docs/sitemap.txt

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          single-commit: true
